[pytest]

testpaths =
    tests
    integration

python_files = test_*.py *_test.py check_*.py


addopts =
    -v
    -s
    --maxfail=50
    --tb=short
    tests/
    --headed
    -m only
    --browser chromium
    --slowmo 1500
    --tracing retain-on-failure
    --video retain-on-failure
    --screenshot on
    --output .test-results
    --alluredir .allure-results
    --url localhost:3000






markers =
    param: тесты с параметризацией
    fixtures
    only
    assertion
    memes


filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning


